name: docker-publish
run-name: Docker Publish

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        image:
          - name: API Gateway
            context: ./api-gateway/
            tag: antonioscardace/api-gateway:latest
          - name: Data Manager
            context: ./data-manager/
            tag: antonioscardace/data-manager:latest
          - name: Spark Metadata
            context: ./spark-metadata/
            tag: antonioscardace/spark-metadata:latest
          - name: User Interface
            context: ./user-interface/
            tag: antonioscardace/user-interface:latest

    #---------------------------------#
    #   Build and Push Docker Image   #
    #   on the DockerHub Registry     #
    #---------------------------------#

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ matrix.image.tag }}
          context: ${{ matrix.image.context }}
          push: true