name: tests
run-name: CI for Testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  #------------------------------#
  #   API Gateway Microservice   #
  #------------------------------#

  test_java_gateway:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: Run Maven Tests
        run: cd api-gateway/ && mvn -B clean package

  #-------------------------------#
  #   Data Manager Microservice   #
  #-------------------------------#

  test_java_manager:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Run Maven Tests
        run: cd data-manager/ && mvn -B clean package

  #---------------------------------#
  #   Spark-Metadata Microservice   #
  #---------------------------------#

  test_python_spark:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: cd spark-metadata/ && pip install -r requirements.txt

      - name: Change the PythonPath
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/spark-metadata/src" >> $GITHUB_ENV

      - name: Run Python Tests
        run: cd spark-metadata/ && pytest tests/